language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "0.10"
  - "4"
  - "5"
  - "6"

before_install:
  - wget http://download.redis.io/releases/redis-3.2.3.tar.gz
  - tar xzf redis-3.2.3.tar.gz
  - cd redis-3.2.3
  - make
  - sudo make install
  - cd ..
  - gem install redis
