language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "0.10"
  - "4.2.6"
  - "5.5.0"

before_install:
  - wget http://download.redis.io/releases/redis-2.8.19.tar.gz
  - tar xzf redis-2.8.19.tar.gz
  - cd redis-2.8.19
  - make
  - sudo make install
  - cd ..
  - gem install redis
